### ISSUE TITLE
duplicated packages

### ISSUE THREAD

**Issue by yaitskov** [nix-community/poetry2nix#348] opened 2021-08-10 21:50 UTC
Hi,

I am trying to build notebook (jupyter) on MacOS Big Sur.
With default config notebook fails due send2trash cannot find  MacOS api.
It is not a big surprise, because bare nix way faces same problem, but I can fix it with overrides.
Overriding send2trash in poetry2nix causes duplicated packages validation error.

toml file:

```
[tool.poetry]
name = "nb"
version = "0.1.0"
description = ""
authors = [x <x@y.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Send2Trash = "^1.8.0"
appnope = "^0.1.2"
jupyter = "^1.0.0"
notebook = "^6.4.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
nb = "nb:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

default default.nix:
```
{ pkgs ? import <nixpkgs> {} }:
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
}
```

initial runtime error message:
> 
> ./result/bin/nb
> Traceback (most recent call last):
>   File "/nix/store/78k3pxwjjg6y1dvisdx0swhg3c4a84lr-python3.8-send2trash-1.8.0/lib/python3.8/site-package> es/send2trash/plat_osx.py", line 14, in <module>
>     from .plat_osx_pyobjc import send2trash
>   File "/nix/store/78k3pxwjjg6y1dvisdx0swhg3c4a84lr-python3.8-send2trash-1.8.0/lib/python3.8/site-packag
> es/send2trash/plat_osx_pyobjc.py", line 7, in <module>
>     from Foundation import NSFileManager, NSURL
> ModuleNotFoundError: No module named 'Foundation'
> 

default.nix with workaround:
```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
with pkgs.python39Packages;
let
  pyobjc-core = buildPythonPackage rec {
    pname = "pyobjc-core";
    version = "7.3";
    adfasdf = true;
    name = "${pname}-${version}";
    src = fetchPypi {
      pname = "pyobjc-core";
      inherit version;
      sha256 = "0x3msrzvcszlmladdpl64s48l52fwk4xlnnri8daq2mliggsx0ah";
    };
    preBuild=''                                                                                          
         export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk"                       
    '';
    CFLAGS = "-iwithsysroot /usr/include -Wno-unused-argument";
    doCheck = false;
    commonPreHook = ''                                                                                   
      export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";  
    '';
    propagatedBuildInputs = [
      pkgs.darwin.libobjc
      pkgs.darwin.cctools
      pkgs.darwin.apple_sdk.frameworks.Foundation
      pkgs.darwin.apple_sdk.frameworks.AppKit
      pkgs.darwin.apple_sdk.frameworks.CoreServices
      pkgs.darwin.apple_sdk.frameworks.Cocoa
      setuptools
    ];
    buildInputs = [ libffi ];
  };

  cocoa = buildPythonPackage rec {
    pname = "pyobjc";
    version = "7.3";
    name = "${pname}-${version}";
    src = fetchPypi {
      pname = "pyobjc-framework-Cocoa";
      inherit version;
      sha256 = "0zhbp18i06aprwfbp06l9wm3qrzsdcyy9hwis5d4b8wmlzkhb3di"; # 7.3 Cocoa                       
    };
    CFLAGS="-Wno-unused-argument -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
    doCheck = false;
    setupPyBuildFlags = [ "-j" "12" ] ;
   propagatedBuildInputs = [
      pyobjc-core
      pkgs.darwin.libobjc
      pkgs.darwin.apple_sdk.frameworks.Foundation
      pkgs.darwin.apple_sdk.frameworks.CoreFoundation
      pkgs.darwin.apple_sdk.frameworks.AppKit
      pkgs.darwin.apple_sdk.frameworks.Cocoa
      pkgs.darwin.apple_sdk.frameworks.CoreServices
      setuptools
    ];
  };

  my-send2trash = buildPythonPackage rec {
    name = "send2trash";
    version = "1.7.1";

    doCheck = !pkgs.stdenv.isDarwin;
    setupPyBuildFlags = [ "-j" "12" ] ;
    src = fetchFromGitHub {
      owner = "arsenetar";
      repo = "${name}";
      rev = "${version}";
      sha256 = "04fyax0jbqvichv1w5gbi5jy3zj3p2npdqq8k2prripl7xam6na9";
    };
    propagatedBuildInputs = [ pyobjc-core cocoa setuptools pytest ];
  };

  p2nix = poetry2nix.overrideScope' (self: super: {
    defaultPoetryOverrides = super.defaultPoetryOverrides.extend (pyself: pysuper: {
      send2trash = my-send2trash;  
    });
  });
in
p2nix.mkPoetryApplication {
  projectDir = ./.;
}
```
error message after nix workaround:
> Found duplicated packages in closure for dependency 'packaging':
>   packaging 20.9 (/nix/store/23slacyrhblpgyfhaqk3nbrzvh3hx2x1-python3.9-packaging-20.9/lib/python3.9/site-packages)
>   packaging 21.0 (/nix/store/2l6qmk1chjjwz923zbv3n1qz54vj84c4-python3.9-packaging-21.0/lib/python3.9/site-packages)
> Found duplicated packages in closure for dependency 'pyparsing':
>   pyparsing 2.4.7 (/nix/store/q312drllfkya6z1cfixp5yhfi2qbwap8-python3.9-pyparsing-2.4.7/lib/python3.9/site-packages)
>   pyparsing 2.4.7 (/nix/store/z53wskla4k0lb5fs387m668g91xmqsjp-python3.9-pyparsing-2.4.7/lib/python3.9/site-packages)
> Found duplicated packages in closure for dependency 'wcwidth':
>   wcwidth 0.2.5 (/nix/store/dj47lkmn8q3gz45wawad541r2drr0qq5-python3.9-wcwidth-0.2.5/lib/python3.9/site-packages)
>   wcwidth 0.2.5 (/nix/store/c1kvpp7g28awy0b4fd1j9smxggd42hz9-python3.9-wcwidth-0.2.5/lib/python3.9/site-packages)
> 
> Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
> builder for '/nix/store/xv96p5159jrw26c3pnzhbxr69k2554va-python3.9-notebook-6.4.2.drv' failed with exit code 1
> cannot build derivation '/nix/store/yh3j4yjk6r254qa736m6wxclqc7f7gwl-python3.9-nb-0.1.0.drv': 1 dependencies couldn't be built
> 
> 

channel is nixpkgs-unstable (6df7b8f398525a2120906a70caff7931125b7c40)

**Comment by adisbladis** [comment] 2021-08-11 00:28
These overrides needs to be moved into the scope of the overlay, it should look something like:
```
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
  overrides = (self: super: {

    pyobjc-core = buildPythonPackage rec {
      pname = "pyobjc-core";
      version = "7.3";
      adfasdf = true;
      name = "${pname}-${version}";
      src = self.fetchPypi {
        pname = "pyobjc-core";
        inherit version;
        sha256 = "0x3msrzvcszlmladdpl64s48l52fwk4xlnnri8daq2mliggsx0ah";
      };
      preBuild=''
           export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk"
      '';
      CFLAGS = "-iwithsysroot /usr/include -Wno-unused-argument";
      doCheck = false;
      commonPreHook = ''
        export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      '';
      propagatedBuildInputs = [
        pkgs.darwin.libobjc
        pkgs.darwin.cctools
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.CoreServices
        pkgs.darwin.apple_sdk.frameworks.Cocoa
        self.setuptools
      ];
      buildInputs = [ libffi ];
    };

    cocoa = buildPythonPackage rec {
      pname = "pyobjc";
      version = "7.3";
      name = "${pname}-${version}";
      src = self.fetchPypi {
        pname = "pyobjc-framework-Cocoa";
        inherit version;
        sha256 = "0zhbp18i06aprwfbp06l9wm3qrzsdcyy9hwis5d4b8wmlzkhb3di"; # 7.3 Cocoa
      };
      CFLAGS="-Wno-unused-argument -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      doCheck = false;
      setupPyBuildFlags = [ "-j" "12" ] ;
      propagatedBuildInputs = [
        self.pyobjc-core
        pkgs.darwin.libobjc
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.CoreFoundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.Cocoa
        pkgs.darwin.apple_sdk.frameworks.CoreServices
        self.setuptools
      ];
    };

    send2trash = self.buildPythonPackage rec {
      name = "send2trash";
      version = "1.7.1";

      doCheck = !pkgs.stdenv.isDarwin;
      setupPyBuildFlags = [ "-j" "12" ] ;
      src = fetchFromGitHub {
        owner = "arsenetar";
        repo = "${name}";
        rev = "${version}";
        sha256 = "04fyax0jbqvichv1w5gbi5jy3zj3p2npdqq8k2prripl7xam6na9";
      };
      propagatedBuildInputs = [ pyobjc-core cocoa setuptools pytest ];
    };

  });
}
```
Beware that I haven't tested the above expression, but I think it should be enough for you to understand what the root cause is.

What's happening now is that you are mixing packages from 2 different python package sets (`python39Packages` and the one created by `poetry2nix`).
Hence we need to pass a function to `poetry2nix` that mutates the set to ensure hermeticity.

**Comment by adisbladis** [comment] 2021-08-11 00:32
Also, it looks to me like you want to add the `nativelib` extras to your `pyproject.toml` and let Poetry deal with those dependencies too:
``` toml
[tool.poetry]
name = "nb"
version = "0.1.0"
description = ""
authors = ["x <x@y.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Send2Trash = {version = "^1.8.0", extras = [ "nativelib" ]}
appnope = "^0.1.2"
jupyter = "^1.0.0"
notebook = "^6.4.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
nb = "nb:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by adisbladis** [comment] 2021-08-11 00:37
Which would probably mean that we are down to a few overrides looking something like:
``` nix

poetry2nix.mkPoetryApplication {
  projectDir = ./.;
  overrides = (self: super: {

    pyobjc-core = super.pyobjc-core.overridePythonAttrs(old: {
      preBuild=''
           export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk"
      '';
      CFLAGS = "-iwithsysroot /usr/include -Wno-unused-argument";
      commonPreHook = ''
        export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      '';
      propagatedBuildInputs = old.propagatedBuildInputs ++ [
        pkgs.darwin.libobjc
        pkgs.darwin.cctools
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.CoreServices
        pkgs.darwin.apple_sdk.frameworks.Cocoa
      ];
      buildInputs = [ pkgs.libffi ];
    });

    pyobjc-framework-cocoa = super.pyobjc-framework-cocoa.overridePythonAttrs(old: {
      CFLAGS="-Wno-unused-argument -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      setupPyBuildFlags = old.setupPyBuildFlags or [ ] ++ [ "-j" "12" ] ;
      propagatedBuildInputs = [
        pkgs.darwin.libobjc
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.CoreFoundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.Cocoa
        pkgs.darwin.apple_sdk.frameworks.CoreServices
      ];
    });

    send2trash = super.send2trash.overridePythonAttrs(old: {
      setupPyBuildFlags = old.setupPyBuildFlags or [ ] ++ [ "-j" "12" ];
    });

  });
}
```

**Comment by adisbladis** [comment] 2021-08-11 01:14
In any case the issue reported is not an issue in `poetry2nix`, so I'm closing this.

Feel free to use the issue thread to ask follow-up questions though :)

**Closed by adisbladis** 2021-08-11 01:14 UTC

**Comment by yaitskov** [comment] 2021-08-11 16:09
Thanks for the quick and through support!

I would disagree with your opinion that it is solely problem of poetry, because
poetry without nix works for me on MacOS for the same toml file without the issue.

Rest of the message is sort off topic, but I think I would be useful to write about futher problems, because jupyter is very popular and there are not enough copy-paste poetry2nix workarounds on the internet.

First proposed solution seems to resolve the issue with duplicated packages, but I get problem with cffi library. I saw lots of issues while making notebook working on pure nix and I don't remember such issue.

```
  clang -iwithsysroot /usr/include -Wno-unused-argument -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/nix/store/ad19ya4siaxhz63w0m8xh97067iahks0-python3-3.9.6/include/python3.9 -c c/_cffi_backend.c -o build/temp.macosx-10.6-x86_64-3.9/c/_cffi_backend.o -iwithsysroot/usr/include/ffi                                                                                                   
  c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found                                           
  #include <ffi.h>                                                                                       
           ^~~~~~~ ```
```

Workaround with adding `extras = [ "nativelib" ]` to toml file gives the same error.
As for me poetry2nix should be a transparent wrapper not affecting toml file anyhow.

Trying further...

```
overrides = (self: super: rec {
     cffi = super.cffi.overrideAttrs(old: {
       CFLAGS = "-iwithsysroot=${libffi.dev}/include  -Wno-unused-argument";
       buildInputs = [ libffi ];
     });
}
```
Solves issue with cffi, but runtime error (Foundation) retains.


```
  pyobjc-core = super.pyobjc-core.overridePythonAttrs(old: {
      preBuild=''
           export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk"
      '';
      CFLAGS = "-iwithsysroot /usr/include -Wno-unused-argument";
      commonPreHook = ''
        export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      '';
      propagatedBuildInputs = old.propagatedBuildInputs ++ [
        pkgs.darwin.libobjc
        pkgs.darwin.cctools
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.CoreServices
        pkgs.darwin.apple_sdk.frameworks.Cocoa
      ];
      buildInputs = [ pkgs.libffi ];
    });

    pyobjc-framework-cocoa = super.pyobjc-framework-cocoa.overridePythonAttrs(old: {
      CFLAGS="-Wno-unused-argument -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk";
      setupPyBuildFlags = old.setupPyBuildFlags or [ ] ++ [ "-j" "12" ] ;
      propagatedBuildInputs = [
        pkgs.darwin.libobjc
        pkgs.darwin.apple_sdk.frameworks.Foundation
        pkgs.darwin.apple_sdk.frameworks.CoreFoundation
        pkgs.darwin.apple_sdk.frameworks.AppKit
        pkgs.darwin.apple_sdk.frameworks.Cocoa
        pkgs.darwin.apple_sdk.frameworks.CoreServices
      ];
    });
```
Snippet above doesn't have effect on the runtime error.

I return to explicit pyobjc-core, cocoa and send2trash.

`no module Foundation` error disappears, but on creating new book:
```
/nix/store/ad19ya4siaxhz63w0m8xh97067iahks0-python3-3.9.6/bin/python3.9: No module named ipykernel_launcher
```
this happens only with poetry2nix.


Don't know what's wrong with ipykernel.
Attempt to upgrade ipykernel version causes duplication of jupyter-core and jupyter-client.
Wow! The circle closed itself :)

To be continued...
