### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by NorfairKing** [nix-community/poetry2nix#810] opened 2022-11-10 14:47 UTC
### Describe the issue 

I see this error for a setup that used to build fine (with rev efe5b281b51c22495c488480d23d7bb1426bf3ba), but no longer builds (with rev 6c2f092d74360102dcc4eb16cc93d562e5d35dcc).
Git bisect found that there are two bad commits:

1. 865bdda37aed07e3bc16f8f85eefb0efac71fb69

Introduces this problem:

```
error: undefined variable 'group'

       at /home/syd/src/niteo/poetry2nix/default.nix:196:33:

          195|                               dev-dependencies.${underscorify pkgMeta.name} or
          196|                                 group.dev.dependencies.${underscorify pkgMeta.name} or # Poetry 1.2.0+
             |                                 ^
          197|                                   { }
```
(This seems to have been fixed in a later commit, because the source already looks different in that location.)

2. 33db1f30d0a4bffdba969f731dc71e67e69038b4

Introduces the infinite loop problem

```
       at /nix/store/bnbh8rbfy3ayd6n3jbv0fdz9dcx5bxa9-nixpkgs-src/lib/attrsets.nix:312:41:

          311|   */
          312|   nameValuePair = name: value: { inherit name value; };
             |                                         ^
          313|
```

It is not at all clear where this came from or how I can reproduce it in a public repository.

### Context

We are using the `nixos-22.05` branch of nixpkgs.
That means poetry 1.1.14, and python 3.9.

**Comment by mrene** [comment] 2022-11-11 17:05
I have the same infinite recursion issue, and can reliably reproduce by creating a pyproject.toml file only referencing tensorflow ([example gist](https://gist.github.com/mrene/7d0a30e38e90456f6e59e499f04978d5))

**Comment by mrene** [comment] 2022-11-12 17:20
#787 fixes this for me (tested by setting the poetry2nix input to `github:nix-community/poetry2nix?ref=refs/pull/787/merge`)

**Comment by lelit** [comment] 2022-11-16 17:14
This is a duplicate of #750, and #787 fixes my flake too, thanks @SemMulder!

**Closed as completed** 2022-12-07 12:21 UTC
