### ISSUE TITLE
External dependency not found

### ISSUE THREAD

**Issue by PhML** [nix-community/poetry2nix#271] opened 2021-03-14 12:50 UTC
I want to install the package `gemmi` which needs `pybind11` as external dependency. So here is my `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = pkgs.python38;
  };
in
pkgs.mkShell {
  buildInputs = [
    pkgs.python38Packages.ipython
    pkgs.python38Packages.poetry
    pkgs.python38Packages.pybind11
    myAppEnv
  ];
}
```
But nix-shell fails:
```
direnv: loading ~/Projects/Xray/.envrc                                                                                                                                                                                         
these derivations will be built:
  /nix/store/j07qbprcjgggmfwnlsjzwxmpls3z4xdg-python3.8-gemmi-0.4.5.drv
  /nix/store/rdwlkqjwv5p1mhdpxwza0imkjaqx6r8b-python3-3.8.8-env.drv
building '/nix/store/j07qbprcjgggmfwnlsjzwxmpls3z4xdg-python3.8-gemmi-0.4.5.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/q2645nchgnfmlfgyyyk8qinjryf9gjp2-gemmi-0.4.5.tar.gz
source root is gemmi-0.4.5
setting SOURCE_DATE_EPOCH to timestamp 1615279874 of file gemmi-0.4.5/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
Processing /build/gemmi-0.4.5
direnv: ([/nix/store/4ikbx711q3ajvsw74m9sqzk02xcrk6cr-direnv-2.27.0/bin/direnv export fish]) is taking a while to execute. Use CTRL-C to give up.
    ERROR: Command errored out with exit status 1:
     command: /nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-t_7c_wc9/setup.py'"'"'; __file__='"'"'/build/pip-req-build-t_7c_wc9/setup.py'"'"';f=getattr(
tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-428zi7ux
         cwd: /build/pip-req-build-t_7c_wc9/
    Complete output (37 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5deaa00>: Failed to establish a new connection: [Er
rno -2] Name or service not known')': /simple/pybind11/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5deabb0>: Failed to establish a new connection: [Er
rno -2] Name or service not known')': /simple/pybind11/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5dea6d0>: Failed to establish a new connection: [Er
rno -2] Name or service not known')': /simple/pybind11/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5deadf0>: Failed to establish a new connection: [Er
rno -2] Name or service not known')': /simple/pybind11/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5e021c0>: Failed to establish a new connection: [Er
rno -2] Name or service not known')': /simple/pybind11/
    ERROR: Could not find a version that satisfies the requirement pybind11>=2.6.0 (from versions: none)
    ERROR: No matching distribution found for pybind11>=2.6.0
    Traceback (most recent call last):
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpb0ukedkx', '--quiet', 'pybind11>=2.6.0']' returned no
n-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-t_7c_wc9/setup.py", line 145, in <module>
        setup(
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/nix/store/zhrml9475rf3c2l4nzwm9330346nm3cy-python3.8-setuptools-50.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpb0ukedkx', '--quiet', 'pybind11>=2.6.0']' returned
non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
builder for '/nix/store/j07qbprcjgggmfwnlsjzwxmpls3z4xdg-python3.8-gemmi-0.4.5.drv' failed with exit code 1
```

Why does it not found `pybind11` ?

**Comment by mickours** [comment] 2021-05-31 21:44
I have a similar issue with `jsonpickle`. It seems that the failed download of `toml` is triggered by this  line in the setup.cfg file:
```toml
setup_requires = setuptools_scm[toml] >= 3.4.1
```
Reference: https://github.com/jsonpickle/jsonpickle/blob/master/setup.cfg#L40

Full logs:
```
building '/nix/store/x86g9lyij9w6f21m989dbgr8q5wqsm9d-python3.8-jsonpickle-2.0.0.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/frrdm02r2d5wgh6v9bw5kr6j2snw56fa-jsonpickle-2.0.0.tar.gz
source root is jsonpickle-2.0.0
setting SOURCE_DATE_EPOCH to timestamp 1612757613 of file jsonpickle-2.0.0/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Removing pyproject.toml...
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/jsonpickle-2.0.0
    ERROR: Command errored out with exit status 1:
     command: /nix/store/xibghivp12jgk2xrwykpxxhy8wbmr5zi-python3-3.8.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-wqg63lpw/setup.py'"'"'; __file__='"'"'/build/pip-req-build-wqg63lpw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-3qm3ray8
         cwd: /build/pip-req-build-wqg63lpw/
    Complete output (38 lines):
    WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b118e0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da3130>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da3280>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da33d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da34f0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
    ERROR: Could not find a version that satisfies the requirement toml (from versions: none)
    ERROR: No matching distribution found for toml
    Traceback (most recent call last):
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/nix/store/xibghivp12jgk2xrwykpxxhy8wbmr5zi-python3-3.8.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/nix/store/xibghivp12jgk2xrwykpxxhy8wbmr5zi-python3-3.8.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmppz6rj_kq', '--quiet', 'toml']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-wqg63lpw/setup.py", line 6, in <module>
        setuptools.setup()
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/nix/store/yvi78c29idymbq5g0l6130sb0wjyvzgn-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/nix/store/xibghivp12jgk2xrwykpxxhy8wbmr5zi-python3-3.8.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmppz6rj_kq', '--quiet', 'toml']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
builder for '/nix/store/x86g9lyij9w6f21m989dbgr8q5wqsm9d-python3.8-jsonpickle-2.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/mdflhfs3dcb84y9bdmscbxxwwcrx4m3v-python3-3.8.8-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/mdflhfs3dcb84y9bdmscbxxwwcrx4m3v-python3-3.8.8-env.drv' failed
```

**Comment by ryneeverett** [comment] 2021-10-05 19:43
This appears to be a duplicate of #42.

**Comment by adisbladis** [comment] 2022-01-05 16:23
Adding dependencies to a top-level shell.nix won't help help with building.
You'll want to use an override which is documented in the README.

**Closed by adisbladis** 2022-01-05 16:23 UTC
